export const teachersApp = "Teachers Helping Teachers is a file-share application that allows teachers to upload or download lesson plans for free. While there are a number of sites and applications that exits with this capability, many are pay-per-lesson or subscription based. As a former teacher, I wanted to create this app to allow the free flow of ideas to assist new and veteran teachers alike, allowing new teachers to learn and veterans to share their wealth of knowledge."

export const kittyKardApp = "Kitty Kard Matching is a game for fans of cats and the old card game Memory. Users enter their name and then click on cards to 'flip' them, revealing pictures of cats. Users try to complete matches as quickly as possible. A timer begins at the start of the game and stops upon completion of the final match. The user's time is their final score and is then displayed among the best times."

export const tvTrackerApp = "TV Tracker is an application in which users can record and track the television series they are watching. Users can log individual shows, what season and episode they are currently on, and whether a show is on the to watch list, being currently watched, or is completed. Shows can be viewed based on what entertainment platform they are on and analytics let users compare platforms. Users can evaluate whether platforms in use are cost effective."

export const developerDescription = "Hi, I'm Eric. I'm a full stack developer with a passion for education and working with communities. Utilizing my experience in Ruby on Rails, JavaScript, and React, I have built applications that streamline file sharing for teachers and track consumers’ usages. My background includes serving as a general education teacher and intervention specialist, as well as having a proven ability to manage and develop programs, staff, and budgets, effectively increasing revenue of non-profit organizations. As a developer, I hope to contribute to companies that invest in their communities, foster a diverse environment, and maintain a healthy fiscal and social approach."

export const teacherDescription = "Prior to becoming a developer, I was an elementary school teacher for the School District of Osceola County and NYC Department of Education."

export const directorDescription = "Aquatics Director/Interim Healthy Lifestyles Director, YMCA. Program Director, Catholic Charities-Afterschool and Camp."

export const runnerDescription = "Finishing the Queen Half Marathon. Got back to running and finished my second half marathon this year. Next year I plan to work up to a full marathon."

export const sportsDescription = "One of the most fun weeks of my life, getting to suit up at Mets Fantasy Camp. While I don't get to do that every year, I do enjoy playing in softball leagues a couple times per year, as well as the occasional basketball league. When I'm not playing, I love attending games to support my favorite teams: the Mets, Nets, Giants, and Devils."

export const scubaDescription = "With the desire to be a part of the search and rescue team as an EMT on my hometown's first aid and rescue squad, I became scuba certified. That became a love and life of its own, becoming an assistant scuba instructor and having the opportunity to dive locally, as well as Grand Cayman, Cozumel, and Belize. My favorite dive site still? The Seas pavillion at Epcot in Walt Disney World."

export const comicsDescription = "As shown, before sports, scuba, and really anything else, there's been comics and superheroes. My love has only grown even more with the rise of the Marvel Cinematic Universe. I love reading through many storylines, old and new, through Marvel Unlimited. If this picture had a caption, it for sure would be, 'The more things change, the more they stay the same'."
